### ISSUE TITLE
Gradle error during tns build

### ISSUE THREAD

**Issue by NachmanRoss** [pboulch/nativescript-wonderpush#1]
The error occurs when building my app for android on Windows 10. The output from the build is further below. I just signed up for a 14 day trial of WonderPush hoping that between it and my using this plugin I would be able to provide push notification to my mobile app. 

I believe that the Gradle output is indicating that a change to my AndroidManifest.xml may fix the build problem but I'm not clear on how I can make the changes that are indicated.

Until I installed this WonderPush plugin I've built and deployed my on android and iOS successfully. All I did was install the plugin, cleaned my environment (I've learned to do this when installing previous plugins created problems. I list my cleaning process further down), and then attempted to build my existing code without adding or making any changes.

Any assistance that you can provide will be greatly appreciated.

### Please, provide the following version numbers that your issue occurs with:

- CLI:  **5.3.1**
- Cross-platform modules: **"5.3.1"**
- Runtime(s):     **"tns-ios": {
      "version": "5.2.0"
    },
    "tns-android": {
      "version": "5.3.1"
    }**
- Plugin(s): 
    ┌──────────────────────────────────┬─────────┐
    │ Plugin                           │ Version │
    │ nativescript-bitmap-factory      │ ^1.7.1  │
    │ nativescript-bottom-navigation   │ ^1.5.0  │
    │ nativescript-camera              │ ^4.4.0  │
    │ nativescript-chatview            │ ^1.0.3  │
    │ nativescript-checkbox            │ ^3.0.3  │
    │ nativescript-clipboard           │ ^1.1.7  │
    │ nativescript-drop-down           │ ^5.0.0  │
    │ nativescript-fingerprint-auth    │ ^6.2.0  │
    │ nativescript-folding-list-view   │ ^1.2.0  │
    │ nativescript-https               │ ^1.0.3  │
    │ nativescript-iqkeyboardmanager   │ ^1.4.0  │
    │ nativescript-local-notifications │ ^3.1.2  │
    │ nativescript-mapbox              │ ^4.4.1  │
    │ nativescript-masked-text-field   │ ^4.0.1  │
    │ nativescript-mediafilepicker     │ ^2.0.16 │
    │ nativescript-menu                │ ^1.0.3  │
    │ nativescript-pdf-view            │ ^2.0.1  │
    │ nativescript-secure-storage      │ ^2.4.0  │
    │ nativescript-social-share        │ ^1.5.1  │
    │ nativescript-stripe              │ ^5.0.8  │
    │ nativescript-toasty              │ ^1.3.0  │
    │ nativescript-ui-calendar         │ ^4.0.0  │
    │ nativescript-ui-chart            │ ^4.0.1  │
    │ nativescript-ui-listview         │ ^6.1.0  │
    │ nativescript-ui-sidedrawer       │ ^6.0.0  │
    │ nativescript-videoplayer         │ ^4.2.1  │
    │ nativescript-wonderpush          │ ^0.1.1  │
    │ rxjs                             │ ~6.3.0  │
    │ tns-core-modules                 │ ^5.3.1  │
    └──────────────────────────────────┴─────────┘
    Dev Dependencies:
    ┌─────────────────────────────┬─────────┐
    │ Plugin                      │ Version │
    │ nativescript-dev-sass       │ ^1.7.0  │
    │ nativescript-dev-typescript │ ~0.7.0  │
    │ nativescript-dev-webpack    │ ^0.19.0 │
    │ nativescript-theme-core     │ ^1.0.4  │
    │ node-sass                   │ ^4.11.0 │
    │ tns-platform-declarations   │ ^5.2.0  │
    │ tslint                      │ ~5.11.0 │
    └─────────────────────────────┴─────────┘

### Please, tell us how to recreate the issue in as much detail as possible. 
(1) - I installed the plugin
(2) - I cleaned and rebuild my environment by running steps 3-5.
(3) I deleted my hooks, node_js, and platforms directories and my package-lock.json file.
(4) - I ran npm -i
(5) - I ran tns platform add android
(6) - I ran tns build android

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

Here's my AndroidMainfest file, output from the tns build android, and a tns plugin command:

My AndroidManifest.xml file (in app/App_Resources/android/src/main):
    <?xml version="1.0" encoding="utf-8"?>
    <manifest
        xmlns:android="http://schemas.android.com/apk/res/android" package="__PACKAGE__" android:versionCode="10000" android:versionName="1.0">
        <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" />
        <uses-sdk android:minSdkVersion="23" android:targetSdkVersion="__APILEVEL__" />
        <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
        <uses-permission android:name="android.permission.INTERNET" />
        <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
        <uses-permission android:name="android.permission.USE_BIOMETRIC" />
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
        <application android:name="com.tns.NativeScriptApplication" android:allowBackup="true"
                    android:icon="@drawable/icon" android:label="@string/app_name"
                    android:theme="@style/AppTheme">
            <service android:name="com.mapbox.services.android.telemetry.service.TelemetryService" />
            <activity android:name="com.tns.NativeScriptActivity" android:label="@string/title_activity_kimera"
                    android:configChanges="keyboardHidden|orientation|screenSize"
                    android:theme="@style/LaunchScreenTheme" android:screenOrientation="unspecified">
                <meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />
                <intent-filter>
                    <action android:name="android.intent.action.MAIN" />
                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
            </activity>
            <activity android:name="com.tns.ErrorReportActivity" />
        </application>
    </manifest>

Output from running tns build android
    Found peer TypeScript 3.1.6
    Preparing project...
    Successfully prepared plugin nativescript-bitmap-factory for android.
    Successfully prepared plugin nativescript-bottom-navigation for android.
    Successfully prepared plugin nativescript-camera for android.
    Successfully prepared plugin nativescript-chatview for android.
    Successfully prepared plugin nativescript-checkbox for android.
    Successfully prepared plugin nativescript-clipboard for android.
    Successfully prepared plugin nativescript-drop-down for android.
    Successfully prepared plugin nativescript-fingerprint-auth for android.
    Successfully prepared plugin nativescript-folding-list-view for android.
    Successfully prepared plugin nativescript-https for android.
    Successfully prepared plugin nativescript-iqkeyboardmanager for android.
    Successfully prepared plugin nativescript-local-notifications for android.
    Successfully prepared plugin nativescript-mapbox for android.
    Successfully prepared plugin nativescript-masked-text-field for android.
    Successfully prepared plugin nativescript-mediafilepicker for android.
    Successfully prepared plugin nativescript-menu for android.
    Successfully prepared plugin nativescript-pdf-view for android.
    Successfully prepared plugin nativescript-secure-storage for android.
    Successfully prepared plugin nativescript-social-share for android.
    Successfully prepared plugin nativescript-stripe for android.
    Successfully prepared plugin nativescript-toasty for android.
    Successfully prepared plugin nativescript-ui-calendar for android.
    Successfully prepared plugin nativescript-ui-chart for android.
    Successfully prepared plugin nativescript-ui-listview for android.
    Successfully prepared plugin nativescript-ui-sidedrawer for android.
    Successfully prepared plugin nativescript-videoplayer for android.
    Successfully prepared plugin nativescript-wonderpush for android.
    Successfully prepared plugin tns-core-modules for android.
    Successfully prepared plugin nativescript-permissions for android.
    Successfully prepared plugin nativescript-ui-core for android.
    Successfully prepared plugin tns-core-modules-widgets for android.
    Project successfully prepared (android)
    All SASS source files removed from app package
    Building project...
    Gradle build...
             + setting applicationId
             + applying user-defined configuration from C:\Users\nachm\NativeScript\KavOr\app\App_Resources\Android\app.gradle
             Applying settings from C:\Users\nachm\NativeScript\KavOr\app\App_Resources\Android\settings.json
             + using support library version 28.0.0
             + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-bottom-navigation\platforms\android\nativescript_bottom_navigation.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-camera\platforms\android\nativescript_camera.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-fingerprint-auth\platforms\android\nativescript_fingerprint_auth.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-local-notifications\platforms\android\app-release.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-mapbox\platforms\android\nativescript_mapbox.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-mediafilepicker\platforms\android\MultiTypeFilePicker-release.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-mediafilepicker\platforms\android\nativescript_mediafilepicker.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-menu\platforms\android\nativescript_menu.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-social-share\platforms\android\nativescript_social_share.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-ui-calendar\platforms\android\TNSCalendar-release.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-ui-chart\platforms\android\TNSChart-release.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-ui-listview\platforms\android\TNSListView-release.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-ui-sidedrawer\platforms\android\TNSSideDrawer-release.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-wonderpush\platforms\android\nativescript_nativescript_wonderpush.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-wonderpush\platforms\android\nativescript_wonderpush.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-wonderpush\platforms\android\wonderpushwrapper.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\nativescript-ui-core\platforms\android\TNSCore-release.aar
             + adding aar plugin dependency: C:\Users\nachm\NativeScript\KavOr\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
    C:\Users\nachm\NativeScript\KavOr\platforms\android\app\src\main\AndroidManifest.xml:46:13-75 Error:
            Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.benalterdevelopment.kavor.wonderpush.fileprovider) from [com.wonderpush:wonderpush-android-sdk:3.0.0] AndroidManifest.xml:46:13-75
            is also present at [:nativescript_camera:] AndroidManifest.xml:15:13-60 value=(com.benalterdevelopment.kavor.provider).
            Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:44:9-56:20 to override.
    C:\Users\nachm\NativeScript\KavOr\platforms\android\app\src\main\AndroidManifest.xml:55:17-63 Error:
            Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/wp_file_provider_paths) from [com.wonderpush:wonderpush-android-sdk:3.0.0] AndroidManifest.xml:55:17-63
            is also present at [:nativescript_camera:] AndroidManifest.xml:20:17-55 value=(@xml/provider_paths).
            Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':app:processDebugManifest'.
    > Manifest merger failed with multiple errors, see logs
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 33s
    Command gradlew.bat failed with exit code 1

**Comment by mmeven** [comment]
Hello @NachmanRoss , sorry for the delay. 

It seems that there is a conflict between the wonderpush plugin and nativescript-camera. Could you provide the package.json file you use ? I will try to look into the issue.

**Comment by NachmanRoss** [comment]
I tried replying via email but my mail provider says that there are invalid characters in the email address. Here's my package.json file.
==================================================
{
  "nativescript": {
    "id": "com.benalterdevelopment.kavor",
    "tns-ios": {
      "version": "5.2.0"
    },
    "tns-android": {
      "version": "5.3.1"
    }
  },
  "description": "A one stop platform that provides an efficient way for businesses and consumers to engage with each other.",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "nativescript-camera": "^4.4.0",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-clipboard": "^1.1.7",
    "nativescript-drop-down": "^5.0.0",
    "nativescript-fingerprint-auth": "^6.2.0",
    "nativescript-folding-list-view": "^1.2.0",
    "nativescript-https": "^1.0.3",
    "nativescript-local-notifications": "^3.1.2",
    "nativescript-mapbox": "^4.4.1",
    "nativescript-masked-text-field": "^4.0.1",
    "nativescript-mediafilepicker": "^2.0.16",
    "nativescript-menu": "^1.0.3",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-secure-storage": "^2.4.0",
    "nativescript-social-share": "^1.5.1",
    "nativescript-stripe": "^5.0.8",
    "nativescript-toasty": "^1.3.0",
    "nativescript-ui-calendar": "^4.0.0",
    "nativescript-ui-chart": "^4.0.1",
    "nativescript-ui-listview": "^6.1.0",
    "nativescript-ui-sidedrawer": "^6.0.0",
    "nativescript-videoplayer": "^4.2.1",
    "nativescript-wonderpush": "^0.1.1",
    "rxjs": "~6.3.0",
    "tns-core-modules": "^5.3.1"
  },
  "devDependencies": {
    "nativescript-dev-sass": "^1.7.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.19.0",
    "nativescript-theme-core": "^1.0.4",
    "node-sass": "^4.11.0",
    "tns-platform-declarations": "^5.2.0",
    "tslint": "~5.11.0"
  },
  "readme": "NativeScript Application",
  "author": "Ben Alter Development, LLC"
}

**Comment by mmeven** [comment]
Alright, could you try to add this part into the `application` tag of the Android manifest :

```
<provider
	android:name="android.support.v4.content.FileProvider"
	android:authorities="${applicationId}.provider"
        tools:replace="android:authorities"
	android:exported="false"
	android:grantUriPermissions="true">
	<meta-data
		android:name="android.support.FILE_PROVIDER_PATHS"
		tools:replace="android:resource"
		android:resource="@xml/provider_paths"/>
</provider>
```
and this : 
```
xmlns:tools="http://schemas.android.com/tools"
```
right under `xmlns:android`. 

Using this is I managed to build an application without error, but I haven't tried anything to see if those plugins still work correctly - could you check on your side if it works correctly ?

The issue is that both plugins declare a FileProvider in their manifests, using the default class, so when the compiler stumbles upon 2 FileProviders with the same name and authority, he stops. I'm no expert on that part though, I may be wrong.

**Comment by NachmanRoss** [comment]
I was able to successfully build my project after incorporating your suggested changes to my AndroidManifest.xml file. I haven't written any code to use the plugin but now I'm in a position to do so. Thank you. I'll close this issue and contact you if I have any problems using the plugin.
